name: financial_kingdom_builder
description: A gamified trading education app that combines kingdom building mechanics with progressive trading education.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # UI & Navigation
  go_router: ^13.2.1
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0
  
  # Network & API
  dio: ^5.4.1
  json_annotation: ^4.8.1
  
  # Storage & Persistence
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  crypto: ^3.0.3
  local_auth: ^2.1.7
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  logger: ^2.0.2+1
  
  # Environment
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
    - .env.dev
    - .env.staging
    - .env.prod

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700